import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import {getServerSession} from "next-auth/next"
import Hydrate from "./components/Hydrate";
import { Roboto } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({weight: ['400', '500', '700'], subsets: ["latin"] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // fetch the user
  const session =  await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body className={`mx-64, ${roboto.className}`}>
        <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
        </Hydrate>
        </body>
    </html>
  );
}
